### ISSUE TITLE
add data_source and data_source_primary_url columns to site data sheet

### ISSUE THREAD

**Issue by westonslaughter** [MacroSHEDS/data_processing#158]
this will be helpful for end users who might want to easily access the actual data source for a site, and will be especially helpful in the case of sites where the network and domain name alone might not make it as easy as it should be to find the exact data source

**Comment by westonslaughter** [comment]
no longer strictly necessary, may still be good idea

**Comment by westonslaughter** [comment]
also, potentially adding "developer" or "lead" or something column, where person who is leading the domain data intake records their initials will help currently and in future

**Comment by vlahm** [comment]
^
