### ISSUE TITLE
get_hdetlim_or_uncer: overlapping detlim dates suspicions

### ISSUE THREAD

**Issue by westonslaughter** [MacroSHEDS/data_processing#172]
![image](https://user-images.githubusercontent.com/63979914/215587726-44dacef1-717a-422d-9b17-e34e998cb67f.png)
![image](https://user-images.githubusercontent.com/63979914/215587797-57f18eb1-7fe8-4d19-bdd7-ae5944c4f493.png)

It seems that the handling for overlapping (aka contradicting) detection limits entries is not fully working (though I may be totally missing something) and while it seems reasonable values are produced as far as I have seen, it is likely worth fully vetting that this function stops or at least warns in situation like shown in the dataframe above. In this dataframe, the source data had an "NA" for the end date on the detlim entry in row four, and it supplies the Sys.Date() as a fill in for the end. This creates a huge overlap. The function also quietly resolved over this provided detlim data which itself overlaps (the original Sleepers detlim info overlaps a lot)

**Comment by vlahm** [comment]
@westonslaughter good catch. i don't remember building any catches for this kind of overlap, so what we probably have now is an arbitrary preference situation. i'm guessing it's rare, but something to resolve so that we have more accurate BDL replacements in v2.
